s1= set()
s1.update(["Alice", "Bob", "Charlie", "David", "Emma"])
print("Set after adding names:",s1)
s1.discard("Charlie") 
s1.add("Charlotte")   
print("Set after modifying a name:",s1)
s1.discard("Alice")
s1.discard("Emma")
print("Set after deleting two names:",s1)
